name: project_flutter
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the build number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# You can manually update the versions or run `flutter pub upgrade`.
dependencies:
  flutter:
    sdk: flutter

  # Adds the Cupertino Icons font to your application. (iOS style icons)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^4.0.0

# Flutter section - contains important settings for Flutter-specific functionalities.
flutter:
  uses-material-design: true

  # Assets section for adding images, icons, or any other static files.
  assets:
    - lib/image.png
    - lib/logo.png
      # Pastikan file gambar ini ada di folder lib/

  # Fonts section for adding custom fonts.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

# The following line ensures that the Material Icons font is
# included with your application, so that you can use the icons in
# the material Icons class.
